cxx.std = experimental
cxx.features.modules = true

using cxx

assert $cxx.features.modules "no modules support for $cxx.signature"

mxx{*}: extension = mxx
cxx{*}: extension = cxx

lib{rope}: cxx{rope}
exe{tests}: cxx{tests tests_main} rope