name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install Nix
      uses: DeterminateSystems/nix-installer-action@v9      

    - name: Build
      run: nix develop '.#cpprope' --command ./build.sh

    - name: Tests on CLang
      run: ./build/clang/run_tests
